apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kitchen-backend
  name: kitchen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kitchen-backend
  template:
    metadata:
      labels:
        io.kompose.service: kitchen-backend
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/micro-restaurant-nestjs-public/kitchen-service:a26c73ddefef351140ac49aacfa86c728ea5d190
          name: kitchen-backend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DINING_SERVICE_URL_WITH_PORT
              value: "dining-backend:3000"
            - name: MONGODB_HOST
              value: "prod-db-mongodb"
            - name: OTLP_URL
              value: "http://jaeger-collector-headless:4318/v1/traces"
      restartPolicy: Always