apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dining-backend
  name: dining-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dining-backend
  template:
    metadata:
      labels:
        io.kompose.service: dining-backend
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/micro-restaurant-nestjs-public/dining-service:a26c73ddefef351140ac49aacfa86c728ea5d190
          name: dining-backend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MENU_SERVICE_URL_WITH_PORT
              value: "menu-backend:3000"
            - name: KITCHEN_SERVICE_URL_WITH_PORT
              value: "kitchen-backend:3000"
            - name: MONGODB_HOST
              value: "prod-db-mongodb"
            - name: OTLP_URL
              value: "http://jaeger-collector.spos-prod.svc.cluster.local:4318/v1/traces"
      restartPolicy: Always